name: GitHub AWS OIDC
on:
  push:
    branches: [main]

  workflow_dispatch: # 👈 Isse GitHub UI me manual option aayega
    inputs:
      terraform_action:
        description: 'Select the action you want to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  oidc-test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::299295683811:role/github-action-role
          aws-region: us-east-1
         

# Optional = aws sts get-caller-identity is the AWS CLI equivalent of asking, "Who am I right now?
      - name: Test AWS Credentials
        run: aws sts get-caller-identity

        
# ===================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.6 # Change this to your preferred Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve -input=false

      - name: Terraform Run Action
        run: terraform ${{ github.event.inputs.terraform_action }} -auto-approve -input=false